inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
  Exclude:
    - 'spec/test_app_templates/**/*'

Metrics/LineLength:
  Max: 200

Metrics/AbcSize:
  Max: 28

Metrics/MethodLength:
  Max: 14

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Rails:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/factories/**/*'

# By default RSpec/MessageSpies has the following:
#   Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'
RSpec/MessageSpies:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false