inherit_from: 
  - .rubocop_todo.yml
#  - .rubocop_fixme.yml

inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/test_app_templates/**/*'
    - 'vendor/**/*'

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'lib/generators/**/*'

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'
    - 'lib/dog_biscuits/models/concerns/metadata_properties/property_sets/*'
    - 'lib/dog_biscuits/models/concerns/metadata_properties/archivematica/archivematica.rb'
    - 'lib/dog_biscuits/models/concerns/extended_solr_document.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/dog_biscuits.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'

# By default RSpec/MessageSpies has the following:
# Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'
RSpec/MessageSpies:
  Enabled: false