language: ruby
sudo: false
rvm:
  - 2.4.0
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=5.0.2"

before_install:
  - gem update --system
before_script:
  - jdk_switcher use oraclejdk8
  - solr_wrapper & fcrepo_wrapper &