language: ruby
sudo: false
rvm:
  - 2.5.3
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - ENGINE_CART_RAILS_OPTIONS='--skip-git --skip-listen --skip-spring'
  matrix:
    - "RAILS_VERSION=5.1.6"

cache:
  bundler: true

before_install:
  - gem update --system
before_script:
  - jdk_switcher use oraclejdk8