language: ruby
sudo: false
rvm:
  - 2.4.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=5.1.4"

cache:
  bundler: true

before_install:
  - gem update --system
before_script:
  - jdk_switcher use oraclejdk8